//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement_MieteView
    {
        public string Abo_Typ { get; set; }
        public int Abo_Wert { get; set; }
        public int Abo_Dauer { get; set; }
        public System.DateTime GueltigAb { get; set; }
        public System.DateTime GueltigBis { get; set; }
        public string Standbetreiber { get; set; }
        public decimal Mietbetrag { get; set; }
        public bool Miete_bezahlt { get; set; }
        public int Mahnstufe { get; set; }
        public Nullable<System.DateTime> GemahntAm { get; set; }
    }
}
