//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonnement()
        {
            this.Abonnement_Areal = new HashSet<Abonnement_Areal>();
            this.AbonnementMiete = new HashSet<AbonnementMiete>();
        }
    
        public int AbonnementId { get; set; }
        public int AbonnementTypId { get; set; }
        public int StandbetreiberId { get; set; }
        public System.DateTime GueltigAb { get; set; }
        public System.DateTime GueltigBis { get; set; }
    
        public virtual Standbetreiber Standbetreiber { get; set; }
        public virtual AbonnementTyp AbonnementTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement_Areal> Abonnement_Areal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonnementMiete> AbonnementMiete { get; set; }
    }
}
