//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonnementView
    {
        public string Name { get; set; }
        public string Abo_Typ { get; set; }
        public int Wert { get; set; }
        public int Dauer { get; set; }
        public System.DateTime GueltigAb { get; set; }
        public System.DateTime GueltigBis { get; set; }
    }
}
