//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adresse()
        {
            this.Areal = new HashSet<Areal>();
            this.Mitglied = new HashSet<Mitglied>();
            this.Wochenmarkt = new HashSet<Wochenmarkt>();
        }
    
        public int AdresseId { get; set; }
        public int OrtId { get; set; }
        public string Strasse { get; set; }
        public int Hausnummer { get; set; }
        public string HausnummerZusatz { get; set; }
        public Nullable<int> StrasseFull { get; set; }
    
        public virtual Ort Ort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Areal> Areal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mitglied> Mitglied { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wochenmarkt> Wochenmarkt { get; set; }
    }
}
