//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anmeldung
    {
        public int AnmeldungId { get; set; }
        public int MitgliedId { get; set; }
        public int BesucherMitgliedId { get; set; }
        public System.DateTime AngemeldetAm { get; set; }
        public bool StatutenUnterschrieben { get; set; }
        public bool BesuchDurchgefuehrt { get; set; }
        public System.DateTime BesuchDurchgefuehrtAm { get; set; }
        public bool BonitaetsPruefungBestanden { get; set; }
        public System.DateTime BonitaetsPruefungBestandenAm { get; set; }
        public Nullable<bool> AnmeldungValid { get; set; }
    
        public virtual Mitglied Besucher { get; set; }
        public virtual Mitglied Mitglied { get; set; }
    }
}
