//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnmeldungView
    {
        public System.DateTime AngemeldetAm { get; set; }
        public string Mitglied { get; set; }
        public string Besucher { get; set; }
        public Nullable<bool> AnmeldungValid { get; set; }
        public bool StatutenUnterschrieben { get; set; }
        public bool BesuchDurchgefuehrt { get; set; }
        public System.DateTime BesuchDurchgefuehrtAm { get; set; }
        public bool BonitaetsPruefungBestanden { get; set; }
        public System.DateTime BonitaetsPruefungBestandenAm { get; set; }
    }
}
