//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Areal()
        {
            this.Abonnement_Areal = new HashSet<Abonnement_Areal>();
            this.Nutzung = new HashSet<Nutzung>();
        }
    
        public int ArealId { get; set; }
        public int AdresseId { get; set; }
        public Nullable<decimal> Laenge { get; set; }
        public Nullable<decimal> Breite { get; set; }
        public Nullable<decimal> Flaeche { get; set; }
        public Nullable<decimal> MietPreis { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement_Areal> Abonnement_Areal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nutzung> Nutzung { get; set; }
    }
}
