//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beurteilung
    {
        public int BeurteilungId { get; set; }
        public int StandbetreiberId { get; set; }
        public int InspektorId { get; set; }
        public System.DateTime BeurteilungAm { get; set; }
        public bool BeurteilungDurchgefuehrt { get; set; }
        public bool Bestanden { get; set; }
    
        public virtual Inspektor Inspektor { get; set; }
        public virtual Standbetreiber Standbetreiber { get; set; }
    }
}
