//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeurteilungView
    {
        public System.DateTime BeurteilungAm { get; set; }
        public string Name_des_Standbetreibers { get; set; }
        public string Name_des_Inspektors { get; set; }
        public bool BeurteilungDurchgefuehrt { get; set; }
        public bool Bestanden { get; set; }
    }
}
