//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspektorView
    {
        public string Name { get; set; }
        public string StrasseFull { get; set; }
        public string PLZ { get; set; }
        public string Bezeichnung { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public bool ProvisorischesMitglied { get; set; }
        public System.DateTime ProbezeitVon { get; set; }
        public System.DateTime ProbezeitBis { get; set; }
    }
}
