//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miete()
        {
            this.AbonnementMiete = new HashSet<AbonnementMiete>();
            this.PlatzMiete = new HashSet<PlatzMiete>();
        }
    
        public int MieteId { get; set; }
        public decimal Betrag { get; set; }
        public bool Bezahlt { get; set; }
        public int Mahnstufe { get; set; }
        public Nullable<System.DateTime> GemahntAm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonnementMiete> AbonnementMiete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatzMiete> PlatzMiete { get; set; }
    }
}
