//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitglied
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mitglied()
        {
            this.Inspektor = new HashSet<Inspektor>();
            this.Nachfrager = new HashSet<Nachfrager>();
            this.Standbetreiber = new HashSet<Standbetreiber>();
            this.Anmeldung = new HashSet<Anmeldung>();
            this.Anmeldung1 = new HashSet<Anmeldung>();
        }
    
        public int MitgliedId { get; set; }
        public int AdresseId { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Name { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public bool ProvisorischesMitglied { get; set; }
        public System.DateTime ProbezeitVon { get; set; }
        public System.DateTime ProbezeitBis { get; set; }
        public bool Abgelehnt { get; set; }
        public string Ablehnungsgrund { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspektor> Inspektor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nachfrager> Nachfrager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Standbetreiber> Standbetreiber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anmeldung> Anmeldung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anmeldung> Anmeldung1 { get; set; }
    }
}
