//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nachfrager
    {
        public int NachfragerId { get; set; }
        public int MitgliedId { get; set; }
    
        public virtual Mitglied Mitglied { get; set; }
    }
}
