//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutzungView
    {
        public string Areal_Stasse { get; set; }
        public string Areal_PLZ { get; set; }
        public string Areal_Ort { get; set; }
        public string Wochenmarkt_Strasse { get; set; }
        public string Wpchenmarktl_PLZ { get; set; }
        public string Wochenmarkt_Ort { get; set; }
        public string Standbetreiber { get; set; }
    }
}
