//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wochenmarkt.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WochenmarktEntities : DbContext
    {
        public WochenmarktEntities()
            : base("name=WochenmarktEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresse { get; set; }
        public virtual DbSet<Beurteilung> Beurteilung { get; set; }
        public virtual DbSet<Inspektor> Inspektor { get; set; }
        public virtual DbSet<Mitglied> Mitglied { get; set; }
        public virtual DbSet<Nachfrager> Nachfrager { get; set; }
        public virtual DbSet<Ort> Ort { get; set; }
        public virtual DbSet<Standbetreiber> Standbetreiber { get; set; }
        public virtual DbSet<Abonnement> Abonnement { get; set; }
        public virtual DbSet<Abonnement_Areal> Abonnement_Areal { get; set; }
        public virtual DbSet<AbonnementMiete> AbonnementMiete { get; set; }
        public virtual DbSet<AbonnementTyp> AbonnementTyp { get; set; }
        public virtual DbSet<Miete> Miete { get; set; }
        public virtual DbSet<PlatzMiete> PlatzMiete { get; set; }
        public virtual DbSet<Areal> Areal { get; set; }
        public virtual DbSet<Nutzung> Nutzung { get; set; }
        public virtual DbSet<Wochenmarkt> Wochenmarkt { get; set; }
        public virtual DbSet<Anmeldung> Anmeldung { get; set; }
    }
}
