select * from app.Ort
select * from app.Adresse
select * from app.Mitglied
select * from app.Standbetreiber
select * from app.Nachfrager
select * from app.Inspektor
select * from app.Beurteilung
select * from app.Anmeldung
select * from invoice.Miete
select * from invoice.AbonnementTyp
select * from invoice.Abonnement
select * from invoice.AbonnementMiete
select * from market.Areal
select * from market.Wochenmarkt
select * from market.Nutzung
select * from invoice.Abonnement_Areal
select * from invoice.PlatzMiete