CREATE SCHEMA [invoice]
        AUTHORIZATION [dbo];
GO

GRANT ALTER, EXECUTE, SELECT ON SCHEMA::[invoice] TO [application] AS [dbo]
GO

GRANT ALTER, DELETE, EXECUTE, INSERT, SELECT, UPDATE ON SCHEMA::[invoice] TO [invoice] AS [dbo]
GO